
<?php echo $this->__("Debit Card"); ?>
<br /><br />
<?php
	
	
	if($_info = $this->getInfo())
	{
		if($_info->getOrder())
		{
			$payment = $_info->getOrder()->getPayment();
			
			if($payment->getAdditionalInformation ('Cielo_error'))
			{
				echo $this->__("Transaction error.");
			}
			else
			{
				$tid = $payment->getAdditionalInformation ('Cielo_tid');
				$status = $payment->getAdditionalInformation ('Cielo_status');
				$cardType = $payment->getAdditionalInformation ('Cielo_cardType');
				$installments = $payment->getAdditionalInformation ('Cielo_installments');
				
				$allCards = Mage::getModel('Brainup_Cielo/cc_types')->toArray();
				$cardType = $allCards[$cardType];
				$installments = ($installments == 1) ? 'à vista' : $installments . " vezes";
				
				$html = "<b>" . $this->__("Transaction") . "</b>: " . $tid . "<br />";
				$html .= "<b>" . $this->__("Status") . "</b>: " . Mage::helper('Brainup_Cielo')->getStatusMessage($status) . "<br />";
				$html .= "<b>" . $this->__("Card Type") . "</b>: " . $cardType;
				
				echo $html;
			}
		}
	}
?>